### PR TITLE
Add Prettier and run against /src

### PR DESCRIPTION
**Pull request by yazeedb**
If there's any interest, integrating Prettier into this project was surprisingly easy. 

**Benefit (IMO)**:
1. Enforcing a style guide in the project and future contributions. ([See their page](https://prettier.io/docs/en/why-prettier.html) for a better explanation :grin:)
2. Contributors using Prettier can now work _with_ it instead of _around_ it.

**Implementation**:
I added a `.prettierrc` with the minimal config to mesh with the existing code style.

Also ran
```bash
node_modules/prettier/bin-prettier.js --write src/**/*.js
``` 

to "fix" everything in `/src`, only 3 files were affected.

### CODE REVIEW

**Comment by lukejacksonn** [comment]
Add the contents of `.prettierrc` to `package.json` under the key `prettier` and run `npx prettier` then I could merge this 👍

**Comment by lukejacksonn** [comment]
Great! No we do not need `.prettierrc` anymore.. it being in the package.json is good enough. Also.. I don't usually add prettier as a dev dependency 🤔as I have it incorporated into my code editor, do you think this is the case for most people?

**Comment by yazeedb** [comment]
Good point. Only benefit I see is running Prettier from `node_modules` instead of requiring global installation. But that's only needed for fixing the codebase style, which this PR already does? 😜 

I'll remove the devDep. We can always add it back if needed.

**Comment by lukejacksonn** [comment]
This looks good to me! Someone on the Chatkit team will have to merge it if they are happy 👍

**Pull request merged**
